"""Initial schema with reference tables

Revision ID: 1ae58f6fda3b
Revises: 
Create Date: 2025-12-24 19:35:05.925257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ae58f6fda3b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_hardware_type', table_name='hardware_options')
    op.drop_table('hardware_options')
    op.drop_index('idx_config_types_code', table_name='configuration_types')
    op.drop_table('configuration_types')
    op.drop_index('idx_frame_series_code', table_name='frame_series')
    op.drop_table('frame_series')
    op.drop_index('idx_glass_types_code', table_name='glass_types')
    op.drop_table('glass_types')
    op.drop_index('idx_frame_colors_code', table_name='frame_colors')
    op.drop_table('frame_colors')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frame_colors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('color_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('color_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('hex_value', sa.VARCHAR(length=7), autoincrement=False, nullable=True),
    sa.Column('rgb_value', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('finish_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='frame_colors_pkey'),
    sa.UniqueConstraint('color_name', name='frame_colors_color_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    comment='Reference data for frame color finishes'
    )
    op.create_index('idx_frame_colors_code', 'frame_colors', ['color_code'], unique=False)
    op.create_table('glass_types',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('glass_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('glass_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('thickness_mm', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('u_factor', sa.NUMERIC(precision=5, scale=3), autoincrement=False, nullable=True),
    sa.Column('shgc', sa.NUMERIC(precision=5, scale=3), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='glass_types_pkey'),
    sa.UniqueConstraint('glass_name', name='glass_types_glass_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    comment='Reference data for glass specifications'
    )
    op.create_index('idx_glass_types_code', 'glass_types', ['glass_code'], unique=False)
    op.create_table('frame_series',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('series_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('series_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('frame_width_mm', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('sash_width_mm', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('nail_fin_width_mm', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('30.00'), autoincrement=False, nullable=True),
    sa.Column('nail_fin_height_mm', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('30.00'), autoincrement=False, nullable=True),
    sa.Column('thermal_break', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('glass_pocket_depth_mm', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='frame_series_pkey'),
    sa.UniqueConstraint('series_code', name='frame_series_series_code_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('series_name', name='frame_series_series_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    comment='Reference data for frame profiles (Series 80, 86, 135, etc.)'
    )
    op.create_index('idx_frame_series_code', 'frame_series', ['series_code'], unique=False)
    op.create_table('configuration_types',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('config_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('config_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('panel_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('operable_panels', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('panel_indicator_style', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('requires_mullions', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('requires_hardware', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='configuration_types_pkey'),
    sa.UniqueConstraint('config_name', name='configuration_types_config_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    comment='Reference data for window/door configurations (Fixed, Casement, Slider, etc.)'
    )
    op.create_index('idx_config_types_code', 'configuration_types', ['config_code'], unique=False)
    op.create_table('hardware_options',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hardware_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('hardware_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('manufacturer', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('model_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('finish', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('applicable_configs', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='hardware_options_pkey'),
    comment='Reference data for hardware options (locks, handles, hinges)'
    )
    op.create_index('idx_hardware_type', 'hardware_options', ['hardware_type'], unique=False)
    # ### end Alembic commands ###
